OUTPUT_DIR = "output"
CARD_IMAGES_DIR = "card_images"


CARD_WIDTH = 1480
CARD_HEIGHT = 2080
CROP_FACTOR = 0.115
TARGET_BLEED_MM = 1
DELETE_CARDS = True



# Defaults 
DEFAULT_CARD_WIDTH = 1480
DEFAULT_CARD_HEIGHT = 2080
DEFAULT_CROP_FACTOR = 0.115
DEFAULT_TARGET_BLEED_MM = 1
DEFAULT_DELETE_CARDS = True
# End of defaults